management.metrics.tags.application: ${spring.application.name}
management.endpoint.health.show-details: always
management.health.diskspace.enabled: false
management.endpoint.logfile.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8080

spring:
#  jackson.serialization.indent_output: true
  application:
    name: athena-api
#  datasource:
#    continue-on-error: false
#    data: classpath:sql/data-derby.sql
#    hikari:
#      connection-test-query: SELECT 1 FROM SYSIBM.SYSDUMMY1
#      maximum-pool-size: 50
#      minimum-idle: 10
#    initialization-mode: embedded
#    name: athenadb
#    platform: derby
#    schema: classpath:sql/schema-derby.sql
#    test-on-borrow: true
#    url: jdbc:derby:memory:athenadb;create=true
#  jpa:
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: false
springfox:
  documentation:
    swagger:
      v2:
        basePath: /athena-api
