management.metrics.tags.application: ${spring.application.name}
management.endpoint.health.show-details: always
management.health.diskspace.enabled: false
management.endpoint.logfile.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8080

spring:
  application:
    name: athena-api
  datasource:
    driver-class-name: 'com.amazon.redshift.jdbc42.Driver'
    url: ${DB_URL}
    #    url: 'jdbc:redshift://examplecluster2.coibnwwmkdkh.ap-south-1.redshift.amazonaws.com:5439/dev'
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: 'org.athena.api.util.CustomRedshiftDialect'
        format_sql: true
    show-sql: false
springfox:
  documentation:
    swagger:
      v2:
        basePath: /athena-api
