apiVersion: v1
kind: Namespace
metadata:
  name: athena
---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: athena
  name: athena-svc-account
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: athena-api
  namespace: athena
spec:
  replicas: 1
  selector:
    matchLabels:
      app: athena-api
  template:
    metadata:
      labels:
        app: athena-api
    spec:
      serviceAccountName: athena-svc-account
      containers:
        - name: athena-api
          imagePullPolicy: Always
          image: localhost:5000/athena-api:1.0.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: DB_URL
              value: "your_redhisht_jdbc_url"
            - name: DB_USER
              value: "your_readshift_cluster_user"
            - name: DB_PASSWORD
              value: "your_readshift_cluster_password"
            - name: ATHENA_ENV
              value: dev
---

apiVersion: v1
kind: Service
metadata:
  name: athena-api
  namespace: athena
spec:
  type: NodePort
  selector:
    app: athena-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
---